baseURL: "https://smhakkinen.github.io/webpage/" 
title: Suvi Häkkinen
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

params:
    description: "This website hosts Suvi H&auml;kkinen's curriculum vitae and contact information."
    author: Suvi Häkkinen
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "December 2025"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: []
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Suvi Häkkinen, PhD
          subtitle: |
            I am a neuroscientist with a multidisciplinary background in engineering, psychology, and clinical imaging. As an Assistant Project Scientist at UC Berkeley, I specialize in mesoscale fMRI, particularly the development of advanced fMRI sequences (VASO, GRASE) on the NexGen 7T scanner and their application to study topics such as hippocampal layer function and large-scale network integration. My academic roots are in engineering (MSc, Aalto University) and auditory neuroscience (PhD, University of Helsinki). I completed postdoctoral fellowships at UCSF and UC Berkeley, specializing in longitudinal modeling of frontotemporal dementia and the structural-functional variability of the cerebral cortex.
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:shakkinen@berkeley.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=wzRTtdQAAAAJ
        - name: GitHub
          url: https://github.com/smhakkinen
        - name: linkedin
          url: https://www.linkedin.com/in/suvi-hakkinen-phd-4386523
#        - name: Twitter
#          url: https://x.com/pmichaillat
#        - name: Bluesky
#          url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Suvi Häkkinen"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
